### ISSUE TITLE
[TASK] Улучшить взаимодействие с программой

### ISSUE THREAD

**Issue by CGOptimum** [742PM/Quiz#133]
# Что сделать?
 - Добавить исчезновение кнопки "подсказка", когда они кончаются
 - Возможно как-то улучшить уведомление о прохождении уровня (текущую надпись плохо видно)
# Зачем?
Упростить пользователям взаимодействие с программой 
# Как?
Редактировать сообщение, возможно выделить специальным шрифтом или символами сообщение о прохождении уровня
# Комментарии

**Comment by FunFunFine** [comment]
Возможно удалять старые кнопки, нажатие которых не ожидается от пользователя.
